export const RECEIVE_ANIMALS = 'RECEIVE_ANIMALS';
export const RECEIVE_ANIMAL_DETAIL = 'RECEIVE_ANIMAL_DETAIL';

export const RECEIVE_NEWS = 'RECEIVE_NEWS';

export const RECEIVE_AUTH = 'RECEIVE_AUTH';
